### PR TITLE
Fix NullPointerException

### PR DESCRIPTION
**Pull request by GorgeousOne**
Fixed the Drug class where two lines were mixed up.

### CODE REVIEW

**Comment by xxCoderforlife** [comment]
_**Currently Testing...**_

**Comment by xxCoderforlife** [comment]
Only issues I've found is Shrooms not having its time and level set up which I believe can be fixed by changing "shrooms" to uppercase in the Drugs.java

**Comment by GorgeousOne** [comment]
😅 guess that was a typo

**Comment by xxCoderforlife** [comment]
@GorgeousOne Do you have a spigot profile? So I may link you as a contributor on the plugin page.

**Comment by GorgeousOne** [comment]
Ye I have one: https://www.spigotmc.org/members/mightyone.258995/

**Pull request merged**
